coverage:
  range: 50...90

  status:
    project:
      default:
        target: 50%
        threshold: 5%

    patch:
      default:
        target: 50%
        threshold: 5%

comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
