version: '3'
services:
  ss-account:
    container_name: ss-account
    build:
      context: .
      dockerfile: ./tests/Dockerfile.test
    command: ./ss-account.test -test.coverprofile=./tests/system.out -test.run '^TestRunMain$$'
    network_mode: "service:ss-server"

  redis:
    image: redis
    network_mode: "service:ss-account"

  ss-server:
    image: ibigbug/shadowsocks-docker
    command: ["ss-server", "-s", "0.0.0.0", "-p", "32384", "-k", "password", "-m", "aes-256-cfb", "--plugin", "obfs-server", "--plugin-opts", "obfs=http"]

  ss-local:
    container_name: ss-local
    image: ibigbug/shadowsocks-docker
    command: ["ss-local", "-l", "1080", "-s", "127.0.0.1", "-p", "9001", "-k", "password", "-m", "aes-256-cfb", "--plugin", "obfs-local", "--plugin-opts", "obfs=http;obfs-host=www.bing.com"]
    network_mode: "service:ss-server"
